version: "3.9"
services:
  sftp:
    build: .
    container_name: sftp_server
    ports:
      - "2222:22"
    volumes:
      - ./scripts/initial_script.sh:/tmp/initial_script.sh
      - ./upload:/home/sftpuser/upload   # carpeta compartida local → contenedor
    command: sftpuser:12345:1001         # usuario:contraseña:UID

